

const pages = {
    backPage:{
        backIndex:()=>import('@/views/backPage/backIndex.vue'),
        updatePassword:()=>import('@/views/backPage/updatePassword.vue'),
    },
    careertalk:{
        careertalkAdd:()=>import('@/views/careertalk/careertalkAdd.vue'),
        careertalkList:()=>import('@/views/careertalk/careertalkList.vue'),
        careertalkUpdate:()=>import('@/views/careertalk/careertalkUpdate.vue'),
    },
    jobfair:{
        jobfairAdd:()=>import('@/views/jobfair/jobfairAdd.vue'),
        jobfairList:()=>import('@/views/jobfair/jobfairList.vue'),
        jobfairUpdate:()=>import('@/views/jobfair/jobfairUpdate.vue'),
    },
    jobs:{
        jobsAdd:()=>import('@/views/jobs/jobsAdd.vue'),
        jobsList:()=>import('@/views/jobs/jobsList.vue'),
        jobsUpdate:()=>import('@/views/jobs/jobsUpdate.vue'),
    },
    www:{
        frontIndex:()=>import('@/views/www/frontIndex.vue'),
        testPage:()=>import('@/views/www/testPage.vue'),
        recruitment:()=>import('@/views/www/recruitment.vue'),
        campusTalkPage:()=>import('@/views/www/campusTalkPage.vue'),
        campusRecruitmentPage:()=>import('@/views/www/campusRecruitmentPage.vue'),
        companyDetailPage:()=>import('@/views/www/companyDetailPage.vue'),
        companyPage:()=>import('@/views/www/companyPage.vue'),
        recruitmentDetailPage:()=>import('@/views/www/recruitmentDetailPage.vue'),
        help:()=>import('@/views/www/help.vue'),
        guidanceVocationalPage:()=>import('@/views/www/guidanceVocationalPage.vue'),
        guidancePolicyDetailPage:()=>import('@/views/www/guidancePolicyDetailPage.vue'),
        guidanceExperiencePage:()=>import('@/views/www/guidanceExperiencePage.vue'),
        guidanceCoachPage:()=>import('@/views/www/guidanceCoachPage.vue'),
        guidance:()=>import('@/views/www/guidance.vue'),
        notice:()=>import('@/views/www/notice.vue'),
        recruitmentBrochureDetailPage:()=>import('@/views/www/recruitmentBrochureDetailPage.vue'),
        recruitmentBrochurePage:()=>import('@/views/www/recruitmentBrochurePage.vue'),
        disLogin:()=>import('@/views/www/disLogin.vue'),
        distRegist:()=>import('@/views/www/distRegist.vue'),
        unitLogin:()=>import('@/views/www/unitLogin.vue'),
        UnitReg:()=>import('@/views/www/UnitReg.vue'),
        UnitReg2:()=>import('@/views/www/UnitReg2.vue'),
        StuReg:()=>import('@/views/www/StuReg.vue'),
        StudentLogin:()=>import('@/views/www/StudentLogin.vue'),
    },
}
export default pages;